apiVersion: v1
kind: Namespace
metadata:
  name: openshift-secrets-management
  labels:
    app.kubernetes.io/name: ocp-secrets-management
    app.kubernetes.io/part-of: ocp-secrets-management-operator
