apiVersion: v1
kind: ServiceAccount
metadata:
  name: secrets-management-operator
  namespace: openshift-secrets-management
  labels:
    app.kubernetes.io/name: ocp-secrets-management
    app.kubernetes.io/part-of: ocp-secrets-management-operator
